development:
  adapter: postgresql
  encoding: unicode
  database: mk_development
  pool: 5
  username: svaroge
  password: crujel

test:
  adapter: postgresql
  encoding: unicode
  database: mk_test
  pool: 5
  username: svaroge
  password: crujel
